apiVersion: internal.odigos.io/v1beta1
kind: OtelDistribution
metadata:
  name: ruby-community
spec:
  name: ruby-community
  language: ruby
  runtimeEnvironments:
    - name: ruby
      supportedVersions: '>=3'
  displayName: 'Ruby Community Native Instrumentation'
  description: |
    This distribution is for Ruby applications using OpenTelemetry Native SDK and instrumentation libraries from the OpenTelemetry community.
  environmentVariables:
    # otlpHttpLocalNode: true
    staticVariables:
      - envName: OTEL_RUBY_RESOURCE_DETECTORS
        envValue: 'container google_cloud_platform azure'
      - envName: OTEL_RUBY_ENABLED_INSTRUMENTATIONS
        envValue: ''
  runtimeAgent:
    directoryNames:
      - '{{ODIGOS_AGENTS_DIR}}/ruby'
    device: 'instrumentation.odigos.io/generic'
    # k8sAttrsViaEnvVars: true
